import type { RepertoireSuggestion, WorkType } from "./types";

export interface CatalogEntry {
  title: string;
  composer: string;
  workTitle?: string;
  workType: WorkType;
  language?: string;
  voiceType?: string;
  era?: string;
  difficulty?: "beginner" | "intermediate" | "advanced";
  tags: string[];
}

export const repertoireCatalog: CatalogEntry[] = [
  {
    title: "Vedrai, carino",
    composer: "Wolfgang Amadeus Mozart",
    workTitle: "Don Giovanni",
    workType: "aria",
    language: "Italian",
    voiceType: "soprano",
    era: "Classical",
    difficulty: "intermediate",
    tags: ["mozart", "soprano", "italian", "aria", "classical", "zerlina", "lyric"],
  },
  {
    title: "Batti, batti, o bel Masetto",
    composer: "Wolfgang Amadeus Mozart",
    workTitle: "Don Giovanni",
    workType: "aria",
    language: "Italian",
    voiceType: "soprano",
    era: "Classical",
    difficulty: "intermediate",
    tags: ["mozart", "soprano", "italian", "aria", "classical", "zerlina"],
  },
  {
    title: "Deh vieni, non tardar",
    composer: "Wolfgang Amadeus Mozart",
    workTitle: "Le nozze di Figaro",
    workType: "aria",
    language: "Italian",
    voiceType: "soprano",
    era: "Classical",
    difficulty: "intermediate",
    tags: ["mozart", "soprano", "italian", "aria", "classical", "figaro", "susanna"],
  },
  {
    title: "Porgi, amor",
    composer: "Wolfgang Amadeus Mozart",
    workTitle: "Le nozze di Figaro",
    workType: "aria",
    language: "Italian",
    voiceType: "soprano",
    era: "Classical",
    difficulty: "advanced",
    tags: ["mozart", "soprano", "italian", "aria", "classical", "countess"],
  },
  {
    title: "Dove sono",
    composer: "Wolfgang Amadeus Mozart",
    workTitle: "Le nozze di Figaro",
    workType: "aria",
    language: "Italian",
    voiceType: "soprano",
    era: "Classical",
    difficulty: "advanced",
    tags: ["mozart", "soprano", "italian", "aria", "classical", "countess"],
  },
  {
    title: "Voi che sapete",
    composer: "Wolfgang Amadeus Mozart",
    workTitle: "Le nozze di Figaro",
    workType: "aria",
    language: "Italian",
    voiceType: "mezzo",
    era: "Classical",
    difficulty: "intermediate",
    tags: ["mozart", "mezzo", "italian", "aria", "classical", "cherubino"],
  },
  {
    title: "Non so più cosa son",
    composer: "Wolfgang Amadeus Mozart",
    workTitle: "Le nozze di Figaro",
    workType: "aria",
    language: "Italian",
    voiceType: "mezzo",
    era: "Classical",
    difficulty: "intermediate",
    tags: ["mozart", "mezzo", "italian", "aria", "classical", "cherubino"],
  },
  {
    title: "Ruhe sanft",
    composer: "Wolfgang Amadeus Mozart",
    workTitle: "Zaide",
    workType: "aria",
    language: "German",
    voiceType: "soprano",
    era: "Classical",
    difficulty: "intermediate",
    tags: ["mozart", "soprano", "german", "aria", "classical"],
  },
  {
    title: "O mio babbino caro",
    composer: "Giacomo Puccini",
    workTitle: "Gianni Schicchi",
    workType: "aria",
    language: "Italian",
    voiceType: "soprano",
    era: "Romantic",
    difficulty: "intermediate",
    tags: ["puccini", "soprano", "italian", "aria", "romantic"],
  },
  {
    title: "Quando m'en vo'",
    composer: "Giacomo Puccini",
    workTitle: "La bohème",
    workType: "aria",
    language: "Italian",
    voiceType: "soprano",
    era: "Romantic",
    difficulty: "intermediate",
    tags: ["puccini", "soprano", "italian", "aria", "romantic", "musetta"],
  },
  {
    title: "Si, mi chiamano Mimì",
    composer: "Giacomo Puccini",
    workTitle: "La bohème",
    workType: "aria",
    language: "Italian",
    voiceType: "soprano",
    era: "Romantic",
    difficulty: "advanced",
    tags: ["puccini", "soprano", "italian", "aria", "romantic", "mimi"],
  },
  {
    title: "Che gelida manina",
    composer: "Giacomo Puccini",
    workTitle: "La bohème",
    workType: "aria",
    language: "Italian",
    voiceType: "tenor",
    era: "Romantic",
    difficulty: "advanced",
    tags: ["puccini", "tenor", "italian", "aria", "romantic", "rodolfo"],
  },
  {
    title: "Nessun dorma",
    composer: "Giacomo Puccini",
    workTitle: "Turandot",
    workType: "aria",
    language: "Italian",
    voiceType: "tenor",
    era: "Romantic",
    difficulty: "advanced",
    tags: ["puccini", "tenor", "italian", "aria", "romantic"],
  },
  {
    title: "Lascia ch'io pianga",
    composer: "George Frideric Handel",
    workTitle: "Rinaldo",
    workType: "aria",
    language: "Italian",
    voiceType: "soprano",
    era: "Baroque",
    difficulty: "intermediate",
    tags: ["handel", "soprano", "italian", "aria", "baroque"],
  },
  {
    title: "Ombra mai fu",
    composer: "George Frideric Handel",
    workTitle: "Serse",
    workType: "aria",
    language: "Italian",
    voiceType: "baritone",
    era: "Baroque",
    difficulty: "intermediate",
    tags: ["handel", "baritone", "italian", "aria", "baroque"],
  },
  {
    title: "Where'er You Walk",
    composer: "George Frideric Handel",
    workTitle: "Semele",
    workType: "aria",
    language: "English",
    voiceType: "tenor",
    era: "Baroque",
    difficulty: "intermediate",
    tags: ["handel", "tenor", "english", "aria", "baroque"],
  },
  {
    title: "Caro mio ben",
    composer: "Tommaso Giordani",
    workType: "art_song",
    language: "Italian",
    voiceType: "high voice",
    era: "Classical",
    difficulty: "beginner",
    tags: ["italian", "art song", "beginner", "high voice", "standard rep"],
  },
  {
    title: "Sebben, crudele",
    composer: "Antonio Caldara",
    workType: "art_song",
    language: "Italian",
    voiceType: "medium voice",
    era: "Baroque",
    difficulty: "beginner",
    tags: ["italian", "art song", "baroque", "beginner", "medium voice"],
  },
  {
    title: "Amarilli, mia bella",
    composer: "Giulio Caccini",
    workType: "art_song",
    language: "Italian",
    voiceType: "medium voice",
    era: "Baroque",
    difficulty: "beginner",
    tags: ["italian", "art song", "baroque", "beginner", "medium voice"],
  },
  {
    title: "Vaghissima sembianza",
    composer: "Stefano Donaudy",
    workType: "art_song",
    language: "Italian",
    voiceType: "high voice",
    era: "Romantic",
    difficulty: "intermediate",
    tags: ["italian", "art song", "high voice", "intermediate"],
  },
  {
    title: "Caro mio ben",
    composer: "Tommaso Giordani",
    workType: "art_song",
    language: "Italian",
    voiceType: "low voice",
    era: "Classical",
    difficulty: "beginner",
    tags: ["italian", "art song", "beginner", "low voice"],
  },
  {
    title: "An die Musik",
    composer: "Franz Schubert",
    workType: "art_song",
    language: "German",
    voiceType: "medium voice",
    era: "Romantic",
    difficulty: "intermediate",
    tags: ["schubert", "german", "lied", "art song", "medium voice"],
  },
  {
    title: "Du bist die Ruh",
    composer: "Franz Schubert",
    workType: "art_song",
    language: "German",
    voiceType: "medium voice",
    era: "Romantic",
    difficulty: "advanced",
    tags: ["schubert", "german", "lied", "art song", "medium voice"],
  },
  {
    title: "Ave Maria",
    composer: "Franz Schubert",
    workTitle: "Ellens Gesang III, D. 839",
    workType: "art_song",
    language: "German",
    voiceType: "high voice",
    era: "Romantic",
    difficulty: "intermediate",
    tags: ["schubert", "german", "lied", "art song", "high voice"],
  },
];

export function toSuggestion(
  entry: CatalogEntry,
  reason: string,
  confidence: number
): RepertoireSuggestion {
  return {
    title: entry.title,
    composer: entry.composer,
    workTitle: entry.workTitle,
    workType: entry.workType,
    language: entry.language,
    voiceType: entry.voiceType,
    era: entry.era,
    difficulty: entry.difficulty,
    reason,
    confidence,
    searchQuery: [entry.title, entry.composer, entry.voiceType].filter(Boolean).join(" "),
  };
}
